### ISSUE TITLE
Fix screenshot for package documentation

### ISSUE THREAD

**Issue by SyrieBianco** [bufbuild/docs.buf.build#19]
In an effort to fix #15, #17 was landed without updating the screenshot to the most recent UI. Will update imminently after addressing a customer concern.

**Comment by mfridman** [comment]
Fixed by 779f377c

See here: https://docs.buf.build/bsr/documentation#package-description

Give it a quick look and if good let's close this issue.

cc @SyrieBianco

**Comment by mfridman** [comment]
Closing. This was completed.
