### ISSUE TITLE
Authoring a template: replace library/go with protocolbuffers/go

### ISSUE THREAD

**Issue by johanbrandhorst** [bufbuild/docs.buf.build#24]
The `Authoring a template` page uses `library/go` as the example plugin, but this plugin has been deprecated in favor of `protocolbuffers/go`. We should update the references.

**Comment by johanbrandhorst** [comment]
This actually probably applies to many parts of the `Remote generation` section.

**Comment by mfridman** [comment]
Before we update this, we should also ensure the latest Go plugin is pushed up to the BSR.

https://buf.build/protocolbuffers/templates/go

**Comment by johanbrandhorst** [comment]
The tracking issue for this is https://github.com/bufbuild/remote-plugins/issues/11

**Comment by johanbrandhorst** [comment]
Both the grpc and protocolbuffer templates are now populated.
