### ISSUE TITLE
Input syntax for buf generate is unclear

### ISSUE THREAD

**Issue by torkelrogstad** [bufbuild/docs.buf.build#49]
I've been experimenting today with doing `buf generate GIT_REPO`, and figuring out how to specify branches, tags and SHAs required me to look at the `buf` source code. Would be nice if this was documented better.

**Comment by bufdev** [comment]
This is all documented here: https://docs.buf.build/reference/inputs - perhaps we should point to it better however, what would have helped here? Any suggestions?

**Comment by torkelrogstad** [comment]
Oh, I totally didn't see that. I was mostly looking at the [generate usage](https://docs.buf.build/generate/usage#common-use-cases), where I saw that it was possible to add a git repo as the input. That made me think it's probably possible to specify a tag/branch/SHA. I guess adding a link to the inputs reference under either "Common use cases" or "Run generate" could make sense?
